### ISSUE TITLE
How should I train the transformer model appropriately?

### ISSUE THREAD

**Issue by Rocable** [ymoslem/OpenNMT-Tutorial#12]
My dataset uses the default sample size of 150 that you provided, and I need to train the en-zh model. What size of dataset do you think is suitable for this model?If you need more information from me, I will reply to you quickly，thank you

**Comment by ymoslem** [comment]
Hello! If you are just testing, you can start with 500,000 sentence pairs (or less to fit into your machine). However, for a real-world model, you need all the (high-quality) data you can find, usually from one million to several millions. You can find data at [OPUS](https://opus.nlpl.eu/). Fine-tuning models from scratch can take from several hours to several days. The tutorial is designed to be on a small dataset, so it does not take very long.

Another approach that several people follow these days is fine-tuning an already pre-trained model. In this case, you can find pre-trained MT models at [Hugging Face](https://huggingface.co/). For example, you can find [OPUS models](https://huggingface.co/Helsinki-NLP/opus-mt-en-zh), and [MADLAD models](https://huggingface.co/google?search_models=madlad). There is also NLLB, but for some reason, it is not very good with Chinese. In order to fine-tune Hugging Face models, you can use their [Transformers](https://github.com/huggingface/transformers) library. There are several tutorials that explain fine-tuning machine translation models with Transforms.

All the best!

**Comment by ymoslem** [comment]
> Hello! If you are just testing, you can start with 500,000 sentence pairs (or less to fit into your machine).

Note that if you are fine-tuning a pre-trained model, you might need much less data than if you are training a model from scratch. This is especially true if the language pair is well-supported by the pre-trained model.
