### ISSUE TITLE
Weighted corpora loaded so far❓

### ISSUE THREAD

**Issue by pariskang** [ymoslem/OpenNMT-Tutorial#7]
![image](https://user-images.githubusercontent.com/13728918/209820684-794dcda6-5e65-4763-b22a-4e755d26ad85.png)
I tested this code on my own dataset with 4k parallel sentence. But when I trained the model, it always shows "Weighted corpora loaded so far", how can I solve this problem. Thank u

**Comment by ymoslem** [comment]
Hello! I see in the screenshot that the cell was still running. What happened after that? Did the training continue or did you receive an error?

The message itself is not a problem. You see it too frequently because the dataset is too small. Generally speaking, you need a larger dataset to obtain good MT results.

**Comment by bruno6000** [comment]
Can anybody answer? I have similar problems and don't know why?

**Comment by ymoslem** [comment]
> Can anybody answer? I have similar problems and don't know why?

The same question and answer in my previous comment. Any errors? What's the size of the training dataset? Have you tried a larger dataset?

**Comment by Rocable** [comment]
is it normal to see the message too frequently?and can you describe what a normal speed looks like?I also want to know how long it usually takes to train a transformer model

**Comment by ymoslem** [comment]
I think this happens when the dataset is too small, and it is just an info message. Nevertheless, after finishing the tutorial with small data, you can try with more data.
